/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */
package org.chromium.ui;

public final class R {
	public static final class color {
		public static final int autofill_dark_divider_color = 0x7f070003;
		public static final int autofill_divider_color = 0x7f070002;
		public static final int color_picker_background_color = 0x7f070001;
		public static final int color_picker_border_color = 0x7f070000;
	}
	public static final class dimen {
		public static final int autofill_text_divider_height = 0x7f080003;
		public static final int autofill_text_height = 0x7f080002;
		public static final int color_button_height = 0x7f080001;
		public static final int color_picker_gradient_margin = 0x7f080000;
		public static final int infobar_button_horizontal_padding = 0x7f080008;
		public static final int infobar_button_text_size = 0x7f080005;
		public static final int infobar_icon_size = 0x7f08000a;
		public static final int infobar_margin = 0x7f080007;
		public static final int infobar_min_size = 0x7f080006;
		public static final int infobar_text_size = 0x7f080004;
		public static final int infobar_touch_target_height = 0x7f080009;
	}
	public static final class drawable {
		public static final int autofill_popup_background = 0x7f020000;
		public static final int autofill_popup_background_down = 0x7f020001;
		public static final int autofill_popup_background_up = 0x7f020002;
		public static final int color_button_background = 0x7f020008;
		public static final int color_picker_advanced_select_handle = 0x7f020009;
		public static final int color_picker_border = 0x7f02000a;
	}
	public static final class id {
		public static final int autofill_label = 0x7f0a000b;
		public static final int autofill_menu_text = 0x7f0a000a;
		public static final int autofill_popup_window = 0x7f0a0000;
		public static final int autofill_sublabel = 0x7f0a000c;
		public static final int color_button_swatch = 0x7f0a003a;
		public static final int color_picker_advanced = 0x7f0a0011;
		public static final int color_picker_simple = 0x7f0a0012;
		public static final int gradient = 0x7f0a000f;
		public static final int gradient_border = 0x7f0a000e;
		public static final int more_colors_button = 0x7f0a0014;
		public static final int more_colors_button_border = 0x7f0a0013;
		public static final int seek_bar = 0x7f0a0010;
		public static final int selected_color_view = 0x7f0a0017;
		public static final int selected_color_view_border = 0x7f0a0016;
		public static final int text = 0x7f0a000d;
		public static final int title = 0x7f0a0015;
	}
	public static final class layout {
		public static final int autofill_text = 0x7f040000;
		public static final int color_picker_advanced_component = 0x7f040001;
		public static final int color_picker_dialog_content = 0x7f040002;
		public static final int color_picker_dialog_title = 0x7f040003;
	}
	public static final class string {
		public static final int color_picker_button_black = 0x7f06000f;
		public static final int color_picker_button_blue = 0x7f06000b;
		public static final int color_picker_button_cancel = 0x7f060007;
		public static final int color_picker_button_cyan = 0x7f06000a;
		public static final int color_picker_button_green = 0x7f06000c;
		public static final int color_picker_button_magenta = 0x7f06000d;
		public static final int color_picker_button_more = 0x7f060002;
		public static final int color_picker_button_red = 0x7f060009;
		public static final int color_picker_button_set = 0x7f060006;
		public static final int color_picker_button_white = 0x7f060010;
		public static final int color_picker_button_yellow = 0x7f06000e;
		public static final int color_picker_dialog_title = 0x7f060008;
		public static final int color_picker_hue = 0x7f060003;
		public static final int color_picker_saturation = 0x7f060004;
		public static final int color_picker_value = 0x7f060005;
		public static final int low_memory_error = 0x7f060000;
		public static final int opening_file_error = 0x7f060001;
	}
	public static final class style {
		public static final int AutofillPopupWindow = 0x7f090000;
	}
}
